apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-concept-1
  name: nginx-concept-1
  namespace: concept-1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-concept-1
  type: LoadBalancer  