apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app-2
  name: nginx-app-2
  namespace: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-2
  template:
    metadata:
      labels:
        app: nginx-app-2
    spec:
      containers:
      - image: nginx-app-2
        name: nginx-app-2
        volumeMounts:
        - name: nginx-config-app-2
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-app-2
        configMap:
          name: nginx-config-app-2