apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-2
  name: nginx-app-2
  namespace: app-2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-app-2
  type: LoadBalancer  