apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactjs-web-app-2
  name: reactjs-web-app-2
  namespace: app-2
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: reactjs-web-app-2
  type: ClusterIP
