apiVersion: v1
kind: Service
metadata:
  labels:
    app: promotion-service
  name: promotion-service
  namespace: concept-1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: promotion-service
  type: ClusterIP
