apiVersion: v1
kind: Service
metadata:
  labels:
    app: main-service-app-2
  name: main-service-app-2
  namespace: app-2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: main-service
  type: ClusterIP
